### ISSUE TITLE
Fatal error caused by incompetability between Carbon_Breadcrumb_DB_Object and Carbon_Breadcrumb_Item_Post

### ISSUE THREAD

**Issue by alpanayotov** [tyxla/carbon-breadcrumbs#14]
Error:
`
Fatal error: Declaration of Carbon_Breadcrumb_Item_Post::set_id() must be compatible with that of Carbon_Breadcrumb_DB_Object::set_id() in /homepages/21/d320322082/htdocs/cayt/wp-content/themes/mentor/includes/carbon-breadcrumb/includes/Carbon_Breadcrumb_Item_Post.php on line 7`

*Possible cause:* server configuration, as it appears only on a particular server
*Possible Solution:* The public method `set_id` declared in the interface Carbon_Breadcrumb_DB_Object should be declared like:
`public function set_id($id = 0);`

**Comment by tyxla** [comment]
Setting a default value for that method in the interface is actually recommended for consistency with the implementing classes. That should definitely fix it: https://github.com/tyxla/carbon-breadcrumbs/commit/dbb0d5cfef17f67ef6feacce88899b9eddaa5c15.

Thanks for reporting!
