### ISSUE TITLE
Usage of the  "carbon_breadcrumbs_item" filter triggers a fatal error

### ISSUE THREAD

**Issue by alpanayotov** [tyxla/carbon-breadcrumbs#29]
Use case:
`add_filter( 'carbon_breadcrumbs_item', 'crb_modify_breadcrumbs_last_item' );`
`function crb_modify_breadcrumbs_last_item( $item ){  }`

Output:
Fatal error: Call to a member function get_link() on a non-object in ..\carbon-breadcrumbs\includes\Carbon_Breadcrumb_Trail_Renderer.php on line 424

**Comment by tyxla** [comment]
It appears that you're not `return`ing a `Carbon_Breadcrumb_Item` instance in the `crb_modify_breadcrumbs_last_item` callback. This is an edge case - you should always return an instance of `Carbon_Breadcrumb_Item` or any of its subclasses in the callback that is hooked on the `carbon_breadcrumbs_item`.

Anyway, it would be best if the failure here is silent, so even if this happens, it simply skips that item.

**Comment by tyxla** [comment]
Done: https://github.com/tyxla/carbon-breadcrumbs/commit/d136cd17fcc317020aa9078852db2d3d72964922

If `$item` is not a `Carbon_Breadcrumb_Item` instance, that item will be skipped.
