### ISSUE TITLE
Tests failed to install on OS X

### ISSUE THREAD

**Issue by Stoyan0v** [tyxla/carbon-breadcrumbs#37]
When run the tests installation command provided in https://github.com/tyxla/carbon-breadcrumbs/blob/master/tests/README.md I get the following error:
`expr: syntax error`

The `wp-tests-config.php` is the default one, missing database credentials.

Then if I run `phpunit` I get the following error:

`Warning: require_once(/path_to_project/wordpress/wp-content/plugins/carbon-breadcrumbs/tmp/wordpress-tests-lib/src//wp-includes/class-phpmailer.php): failed to open stream: No such file or directory in /path_to_project/wordpress/wp-content/plugins/carbon-breadcrumbs/tmp/wordpress-tests-lib/includes/mock-mailer.php on line 2`.

I checked for that directory and it's missing, so I guess something is broken in installation.

Mac OS X Sierra

**Comment by tyxla** [comment]
Fixed in #38
