### ISSUE TITLE
Apply Filter Triggers `Too Few Arguments Fatal Error`

### ISSUE THREAD

**Issue by lloy0076** [tyxla/carbon-breadcrumbs#42]
This triggers a WordPress error in WordPress 4.9.18 when the `apply_filter` is called:

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function WC_Template_Loader::unsupported_theme_title_filter(), 1 passed in
> BASE\wp-includes\class-wp-hook.php on line 286 and exactly 2 expected in 
> BASE\wp-content\plugins\woocommerce\includes\class-wc-template-loader.php:399 Stack trace: #0
> BASE\wp-includes\class-wp-hook.php(286): WC_Template_Loader::unsupported_theme_title_filter('A New Page') #1
> BASE\wp-includes\plugin.php(203): WP_Hook->apply_filters('A New Page', Array) #2
> BASE\wp-content\themes\braun-parts\vendor\tyxla\carbon-breadcrumbs\core\Carbon_Breadcrumb_Item_Post.php(30): apply_filters('the_title', 'A New Page') #3
> BASE\wp-content\themes\ in
> BASE\wp-content\plugins\woocommerce\includes\class-wc-template-loader.php on line 399

I triggered this by installing WooCommerce _but_ I don't believe it is WooCommerce specific and I think the offending line is:

https://github.com/tyxla/carbon-breadcrumbs/blob/8a30f5a0a6c493ad47ea7239fa4ca38870c1f382/core/Carbon_Breadcrumb_Item_Post.php#L30

More info and a probable solution is here:

https://toolset.com/forums/topic/views-conflict-with-woocommerce/#post-616606

**Comment by lloy0076** [comment]
https://github.com/tyxla/carbon-breadcrumbs/blob/8a30f5a0a6c493ad47ea7239fa4ca38870c1f382/core/Carbon_Breadcrumb_Item_Term.php#L46

https://github.com/tyxla/carbon-breadcrumbs/blob/8a30f5a0a6c493ad47ea7239fa4ca38870c1f382/core/Carbon_Breadcrumb_Trail_Renderer.php#L385

https://github.com/tyxla/carbon-breadcrumbs/blob/8a30f5a0a6c493ad47ea7239fa4ca38870c1f382/core/Carbon_Breadcrumb_Trail_Renderer.php#L114

https://github.com/tyxla/carbon-breadcrumbs/blob/8a30f5a0a6c493ad47ea7239fa4ca38870c1f382/core/Carbon_Breadcrumb_Trail.php#L42

**Comment by tyxla** [comment]
Hey @lloy0076! Thanks for reporting! This appears easy to fix, stay tuned.

**Comment by tyxla** [comment]
This is fixed by #43.
